name: BuildAction  # このworkflowの名前
description: "pushしたらビルドする、そしてデプロイ" # このworkflowの説明

on: push

jobs: # jobsで実行する内容を書く
  build: # 実行する内容(job)の名前
    name: build
    runs-on: ubuntu-latest # 実行するOS
    steps:
      # リポジトリをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.jsを使用する
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      # 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # ビルドを実行
      - name: Run build
        run: npm run build


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      # リポジトリをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.jsを使用する
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'
          cache: "npm"

      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools

      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: change space
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}

