name: BuildAction  # このworkflowの名前
description: "pushしたらビルドする" # このworkflowの説明

on: push

jobs: # jobsで実行する内容を書く
  say_hello: # 実行する内容(job)の名前
    runs-on: ubuntu-latest # 実行するOS
    steps:
      # ビルドを実行
      - name: Run build
        run: npm run build